FROM php:7.4-fpm-alpine

MAINTAINER Mykyta Popov <mr.mykyta.popov@gmail.com>

RUN apk update \
# Add new group and new user
    && addgroup -g 1000 -S dev \
    && adduser -u 1000 -s /bin/ash -D -G dev dev \
# Create workdir
    && mkdir /app \
    && chown -R dev:dev /app \
# Configure user for fpm
    && apk add sed \
    && sed -i 's|user = www-data|user = dev|' /usr/local/etc/php-fpm.d/www.conf \
    && sed -i 's|group = www-data|group = dev|' /usr/local/etc/php-fpm.d/www.conf \
# deps
    && apk add --no-cache $PHPIZE_DEPS openssl-dev \
# Install xdebug
    && docker-php-ext-install pcntl \
    && pecl install xdebug redis \
    && docker-php-ext-enable xdebug redis \
# Install xhprof
    && apk add --update --no-cache graphviz \
    && pecl install xhprof \
    && docker-php-ext-enable xhprof \
# Install composer
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer \
# Install Git
    && apk add --no-cache bash git openssh

WORKDIR /app
