version: '3'
services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./..:/app
      - ./logs:/var/log/nginx
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  php:
    build:
      context: .
    dns: 8.8.8.8
    restart: always
    volumes:
      - ./..:/app
      - ~/.ssh:/home/dev/.ssh
      - ~/.gitconfig:/home/dev/.gitconfig:ro
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./xhprof.ini:/usr/local/etc/php/conf.d/xhprof.ini
